test_that("Sphincs+ keys generation (shake, 128, small)", {

  k <- keygen_sphincs(category = 128, type = "small")
  expect_s3_class(k, "pqcrypto_keypair")
  expect_equal(k$algorithm, "sphincs+")
  expect_s3_class(k$private, "pqcrypto_private_key")
  expect_equal(length(k$private), 64)
  expect_equal(attr(k$private, "algorithm"), "sphincs+")
  expect_equal(attr(k$private, "params")$hash, "shake")
  expect_equal(attr(k$private, "params")$category, 128)
  expect_equal(attr(k$private, "params")$type, "small")
  expect_s3_class(k$public, "pqcrypto_public_key")
  expect_equal(length(k$public), 32)
  expect_equal(attr(k$public, "algorithm"), "sphincs+")
  expect_equal(attr(k$public, "params")$hash, "shake")
  expect_equal(attr(k$public, "params")$category, 128)
  expect_equal(attr(k$public, "params")$type, "small")
})

test_that("Sphincs+ keys generation (shake, 128, fast)", {

  k <- keygen_sphincs(category = 128, type = "fast")
  expect_s3_class(k, "pqcrypto_keypair")
  expect_equal(k$algorithm, "sphincs+")
  expect_s3_class(k$private, "pqcrypto_private_key")
  expect_equal(length(k$private), 64)
  expect_equal(attr(k$private, "algorithm"), "sphincs+")
  expect_equal(attr(k$private, "params")$hash, "shake")
  expect_equal(attr(k$private, "params")$category, 128)
  expect_equal(attr(k$private, "params")$type, "fast")
  expect_s3_class(k$public, "pqcrypto_public_key")
  expect_equal(length(k$public), 32)
  expect_equal(attr(k$public, "algorithm"), "sphincs+")
  expect_equal(attr(k$public, "params")$hash, "shake")
  expect_equal(attr(k$public, "params")$category, 128)
  expect_equal(attr(k$public, "params")$type, "fast")
})

test_that("Sphincs+ keys generation (shake, 192, small)", {

  k <- keygen_sphincs(category = 192, type = "small")
  expect_s3_class(k, "pqcrypto_keypair")
  expect_equal(k$algorithm, "sphincs+")
  expect_s3_class(k$private, "pqcrypto_private_key")
  expect_equal(length(k$private), 96)
  expect_equal(attr(k$private, "algorithm"), "sphincs+")
  expect_equal(attr(k$private, "params")$hash, "shake")
  expect_equal(attr(k$private, "params")$category, 192)
  expect_equal(attr(k$private, "params")$type, "small")
  expect_s3_class(k$public, "pqcrypto_public_key")
  expect_equal(length(k$public), 48)
  expect_equal(attr(k$public, "algorithm"), "sphincs+")
  expect_equal(attr(k$public, "params")$hash, "shake")
  expect_equal(attr(k$public, "params")$category, 192)
  expect_equal(attr(k$public, "params")$type, "small")
})

test_that("Sphincs+ keys generation (shake, 192, fast)", {

  k <- keygen_sphincs(category = 192, type = "fast")
  expect_s3_class(k, "pqcrypto_keypair")
  expect_equal(k$algorithm, "sphincs+")
  expect_s3_class(k$private, "pqcrypto_private_key")
  expect_equal(length(k$private), 96)
  expect_equal(attr(k$private, "algorithm"), "sphincs+")
  expect_equal(attr(k$private, "params")$hash, "shake")
  expect_equal(attr(k$private, "params")$category, 192)
  expect_equal(attr(k$private, "params")$type, "fast")
  expect_s3_class(k$public, "pqcrypto_public_key")
  expect_equal(length(k$public), 48)
  expect_equal(attr(k$public, "algorithm"), "sphincs+")
  expect_equal(attr(k$public, "params")$hash, "shake")
  expect_equal(attr(k$public, "params")$category, 192)
  expect_equal(attr(k$public, "params")$type, "fast")
})

test_that("Sphincs+ keys generation (default, default, default)", {

  k <- keygen_sphincs()
  expect_s3_class(k, "pqcrypto_keypair")
  expect_equal(k$algorithm, "sphincs+")
  expect_s3_class(k$private, "pqcrypto_private_key")
  expect_equal(length(k$private), 96)
  expect_equal(attr(k$private, "algorithm"), "sphincs+")
  expect_equal(attr(k$private, "params")$hash, "shake")
  expect_equal(attr(k$private, "params")$category, 192)
  expect_equal(attr(k$private, "params")$type, "fast")
  expect_s3_class(k$public, "pqcrypto_public_key")
  expect_equal(length(k$public), 48)
  expect_equal(attr(k$public, "algorithm"), "sphincs+")
  expect_equal(attr(k$public, "params")$hash, "shake")
  expect_equal(attr(k$public, "params")$category, 192)
  expect_equal(attr(k$public, "params")$type, "fast")
})

test_that("Sphincs+ keys generation (shake, 256, small)", {

  k <- keygen_sphincs(category = 256, type = "small")
  expect_s3_class(k, "pqcrypto_keypair")
  expect_equal(k$algorithm, "sphincs+")
  expect_s3_class(k$private, "pqcrypto_private_key")
  expect_equal(length(k$private), 128)
  expect_equal(attr(k$private, "algorithm"), "sphincs+")
  expect_equal(attr(k$private, "params")$hash, "shake")
  expect_equal(attr(k$private, "params")$category, 256)
  expect_equal(attr(k$private, "params")$type, "small")
  expect_s3_class(k$public, "pqcrypto_public_key")
  expect_equal(length(k$public), 64)
  expect_equal(attr(k$public, "algorithm"), "sphincs+")
  expect_equal(attr(k$public, "params")$hash, "shake")
  expect_equal(attr(k$public, "params")$category, 256)
  expect_equal(attr(k$public, "params")$type, "small")
})

test_that("Sphincs+ keys generation (shake, 256, small)", {

  k <- keygen_sphincs(category = 256, type = "fast")
  expect_s3_class(k, "pqcrypto_keypair")
  expect_equal(k$algorithm, "sphincs+")
  expect_s3_class(k$private, "pqcrypto_private_key")
  expect_equal(length(k$private), 128)
  expect_equal(attr(k$private, "algorithm"), "sphincs+")
  expect_equal(attr(k$private, "params")$hash, "shake")
  expect_equal(attr(k$private, "params")$category, 256)
  expect_equal(attr(k$private, "params")$type, "fast")
  expect_s3_class(k$public, "pqcrypto_public_key")
  expect_equal(length(k$public), 64)
  expect_equal(attr(k$public, "algorithm"), "sphincs+")
  expect_equal(attr(k$public, "params")$hash, "shake")
  expect_equal(attr(k$public, "params")$category, 256)
  expect_equal(attr(k$public, "params")$type, "fast")
})

test_that("Keys generation fails on wrong parameters", {

  expect_error(keygen_sphincs(1, 128, "small"))
  expect_error(keygen_sphincs("1", 128, "small"))
  expect_error(keygen_sphincs(NULL, 128, "small"))
  expect_error(keygen_sphincs(NA, 128, "small"))
  expect_error(keygen_sphincs("shake", 1024, "small"))
  expect_error(keygen_sphincs("shake", "strenght", "small"))
  expect_error(keygen_sphincs("shake", NULL, "small"))
  expect_error(keygen_sphincs("shake", NA, "small"))
  expect_error(keygen_sphincs("shake", 128, 1))
  expect_error(keygen_sphincs("shake", 128, "type"))
  expect_error(keygen_sphincs("shake", 128, NULL))
  expect_error(keygen_sphincs("shake", 128, NA))
})
