# Generated by cpp11: do not edit by hand

cpp_keygen_kyber512 <- function() {
  .Call(`_pqcrypto_cpp_keygen_kyber512`)
}

cpp_keygen_kyber768 <- function() {
  .Call(`_pqcrypto_cpp_keygen_kyber768`)
}

cpp_keygen_kyber1024 <- function() {
  .Call(`_pqcrypto_cpp_keygen_kyber1024`)
}

sha_3_512 <- function(input) {
  .Call(`_pqcrypto_sha_3_512`, input)
}
