# Generated by cpp11: do not edit by hand

cpp_decap_kyber512 <- function(secret_key, cipher_text) {
  .Call(`_pqcrypto_cpp_decap_kyber512`, secret_key, cipher_text)
}

cpp_decap_kyber768 <- function(secret_key, cipher_text) {
  .Call(`_pqcrypto_cpp_decap_kyber768`, secret_key, cipher_text)
}

cpp_decap_kyber1024 <- function(secret_key, cipher_text) {
  .Call(`_pqcrypto_cpp_decap_kyber1024`, secret_key, cipher_text)
}

cpp_encap_kyber512 <- function(pub_key) {
  .Call(`_pqcrypto_cpp_encap_kyber512`, pub_key)
}

cpp_encap_kyber768 <- function(pub_key) {
  .Call(`_pqcrypto_cpp_encap_kyber768`, pub_key)
}

cpp_encap_kyber1024 <- function(pub_key) {
  .Call(`_pqcrypto_cpp_encap_kyber1024`, pub_key)
}

cpp_keygen_dilithium2 <- function() {
  .Call(`_pqcrypto_cpp_keygen_dilithium2`)
}

cpp_keygen_dilithium3 <- function() {
  .Call(`_pqcrypto_cpp_keygen_dilithium3`)
}

cpp_keygen_dilithium5 <- function() {
  .Call(`_pqcrypto_cpp_keygen_dilithium5`)
}

cpp_keygen_kyber512 <- function() {
  .Call(`_pqcrypto_cpp_keygen_kyber512`)
}

cpp_keygen_kyber768 <- function() {
  .Call(`_pqcrypto_cpp_keygen_kyber768`)
}

cpp_keygen_kyber1024 <- function() {
  .Call(`_pqcrypto_cpp_keygen_kyber1024`)
}
