

#' Kyber shared secret/shared key encapsulation
#'
#' @param encapsulation  Received encapsulation object.
#' @param private_key   Receiver's private key as generated by `keygen_kyber()`.
#'
#' @return The shared secret
#'
#' @export
#'
#' @examples
#'
decap_kyber <- function(encapsulation, private_key) {

  if (attr(private_key, "param") == 512) {
    out <- cpp_decap_kyber512(private_key, encapsulation)
  } else if (attr(private_key, "param") == 768) {
    out <- cpp_decap_kyber768(private_key, encapsulation)
  } else if (attr(private_key, "param") == 1024) {
    out <- cpp_decap_kyber1024(private_key, encapsulation)
  } else {
    stop("The suplied private key has invalid parameters.")
  }

  return(out)
}
