

#' Kyber shared secret/shared key encapsulation
#'
#' @param encapsulation  Received encapsulation object.
#' @param private_key   Receiver's private key as generated by `keygen_kyber()`.
#'
#' @return The shared secret
#'
#' @export
#'
#' @examples
#' key <- keygen_kyber(512)
#' ss1 <- encap_kyber(key$public)  # This generates an encapsulation readable only by key$private
#' ss2 <- decap_kyber(ss1$encapsulation, key$private)
#' identical(ss1$shared_secret, ss2)
#'
decap_kyber <- function(encapsulation, private_key) {

  if (!inherits(private_key, "pqcrypto_private_key")) {
    stop("'private_key' parameter does not have the expected class.")
  }

  if (attr(private_key, "algorithm") != "kyber") {
    stop("Wrong private key type. Make sure you are using a 'Kyber' private key.")
  }

  if (attr(private_key, "param") == 512) {
    out <- cpp_decap_kyber512(private_key, encapsulation)
  } else if (attr(private_key, "param") == 768) {
    out <- cpp_decap_kyber768(private_key, encapsulation)
  } else if (attr(private_key, "param") == 1024) {
    out <- cpp_decap_kyber1024(private_key, encapsulation)
  } else {
    stop("The suplied private key has invalid parameters.")
  }

  return(out)
}
