
#' Kyber Shared Secret - Retrieve
#'
#' Uses own private key to retrieve the secret key created by `encap_kyber()`.
#'
#' @param encapsulation Received encapsulation object created by `encap_kyber()`
#' @param private_key   Receiver's private key as generated by `keygen_kyber()`.
#'
#' @return The shared secret
#'
#' @export
#'
#' @examples
#' key <- keygen_kyber(512)
#' ss1 <- encap_kyber(key$public)  # This generates an encapsulation readable only by key$private
#' ss2 <- decap_kyber(ss1$encapsulation, key$private)
#' identical(ss1$shared_secret, ss2)
#'
decap_kyber <- function(encapsulation, private_key) {


  if (!inherits(private_key, "pqcrypto_private_key")) {
    pq_stop(c(x = "'private_key' parameter does not have the expected class.",
              i = "'private_key' must have `pqcrypto_private_key` class."))
  }

  if (attr(private_key, "algorithm") != "kyber") {
    pq_stop(c(x = "Wrong private key algorithm.",
              i = "Make sure you are using a 'Kyber' private key."))
  }

  if (attr(private_key, "param") == 512) {
    out <- cpp_decap_kyber512(private_key, encapsulation)
  } else if (attr(private_key, "param") == 768) {
    out <- cpp_decap_kyber768(private_key, encapsulation)
  } else if (attr(private_key, "param") == 1024) {
    out <- cpp_decap_kyber1024(private_key, encapsulation)
  } else {
    pq_stop(c(x = "The suplied private key has invalid parameters."))
  }
  class(out) <- "pqcrypto_shared_secret"

  invisible(out)
}
