
#' Shared Secret - Create ML-KEM (FIPS 203)
#'
#' @description
#' Creates a shared secret key and encapsulates it for secure transmission.
#'
#' @param pub_key  Receiver's public key as generated by `keygen_ml_kem()`.
#'
#' @return A list of two elements with a secret key and its encapsulation to be shared with the
#'    owner of the used public key.
#'
#' @export
#'
#' @examples
#' key <- keygen_ml_kem(512)
#' ss <- encapsulate_ml_kem(key$public)  # This generates an encapsulation readable only by key$private
#'
encapsulate_ml_kem <- function(pub_key) {

  if (!inherits(pub_key, "pqcrypto_public_key")) {
    pq_stop(c(x = "'pub_key' parameter does not have the expected class.",
              i = "'pub_key' must have `pqcrypto_public_key` class."))
  }

  if (!grepl("1.3.6.1.4.1.54392.5.1859.1.1.?", attr(pub_key, "algorithm"))) {
    pq_stop(c(x = "Wrong public key algorithm.",
              i = "Make sure you are using a 'ML-KEM' public key."))
  }

  if (attr(pub_key, "algorithm") == "1.3.6.1.4.1.54392.5.1859.1.1.1") {
    out <- cpp_encap_kyber512(pub_key)
  } else if (attr(pub_key, "algorithm") == "1.3.6.1.4.1.54392.5.1859.1.1.2") {
    out <- cpp_encap_kyber768(pub_key)
  } else if (attr(pub_key, "algorithm") == "1.3.6.1.4.1.54392.5.1859.1.1.3")  {
    out <- cpp_encap_kyber1024(pub_key)
  } else {
    pq_stop(c(x = "The suplied public key has invalid parameters."))
  }

  encap <- list(shared_secret = structure(out[[2]],
                                          class = "pqcrypto_shared_secret"),
                encapsulation = structure(out[[1]],
                                          class = "pqcrypto_encapsulation"))
  return(encap)
}

#' Kyber Shared Secret - Create
#'
#' @description
#' `r lifecycle::badge("deprecated")`
#' Creates a shared secret key and encapsulates it for secure transmission.
#'
#' @param pub_key  Receiver's public key as generated by `keygen_ml_kem()`.
#'
#' @return A list of two elements with a secret key and its encapsulation to be shared with the
#'    owner of the used public key.
#'
#' @export
#' @keywords internal
#'
#' @examples
#' key <- keygen_ml_kem(512)
#' ss <- encap_kyber(key$public)
#' # ->
#' ss <- encapsulate_ml_kem(key$public)
#'
encap_kyber <- function(pub_key) {
  lifecycle::deprecate_soft("0.3.0", "encap_kyber()", "encapsulate_ml_kem()")

  encapsulate_ml_kem(pub_key)

}
