

#' Kyber shared secret/shared key encapsulation
#'
#' @param pub_key  Receiver's public key as generated by `keygen_kyber()`.
#'
#' @return A secret key and its encapsulation to be shared with the owner of the used public key.
#'
#' @export
#'
#' @examples
#' key <- keygen_kyber(512)
#' ss <- encap_kyber(key$public)  # This generates an encapsulation readable only by key$private
#'
encap_kyber <- function(pub_key) {

  if (!inherits(pub_key, "pqcrypto_public_key")) {
    stop("'pub_key' parameter does not have the expected class.")
  }

  if (attr(pub_key, "algorithm") != "kyber") {
    stop("Wrong public key type. Make sure you are using a 'Kyber' public key.")
  }

  if (attr(pub_key, "param") == 512) {
    out <- cpp_encap_kyber512(pub_key)
  } else if (attr(pub_key, "param") == 768) {
    out <- cpp_encap_kyber768(pub_key)
  } else if (attr(pub_key, "param") == 1024)  {
    out <- cpp_encap_kyber1024(pub_key)
  } else {
    stop("Unknown key parameters set.")
  }

  encap <- list(shared_secret = out[[2]],
                encapsulation = out[[1]])
  class(encap) <- c("encapsulation", "kyber")

  return(encap)
}
