
#' Kyber Shared Secret - Create
#'
#' Creates a secret key and encapsulates it for secure transmission.
#'
#' @param pub_key  Receiver's public key as generated by `keygen_kyber()`.
#'
#' @return A secret key and its encapsulation to be shared with the owner of the used public key.
#'
#' @export
#'
#' @examples
#' key <- keygen_kyber(512)
#' ss <- encap_kyber(key$public)  # This generates an encapsulation readable only by key$private
#'
encap_kyber <- function(pub_key) {

  if (!inherits(pub_key, "pqcrypto_public_key")) {
    pq_stop(c(x = "'pub_key' parameter does not have the expected class.",
              i = "'pub_key' must have `pqcrypto_public_key` class."))
  }

  if (attr(pub_key, "algorithm") != "kyber") {
    pq_stop(c(x = "Wrong public key algorithm.",
              i = "Make sure you are using a 'Kyber' public key."))
  }

  if (attr(pub_key, "param") == 512) {
    out <- cpp_encap_kyber512(pub_key)
  } else if (attr(pub_key, "param") == 768) {
    out <- cpp_encap_kyber768(pub_key)
  } else if (attr(pub_key, "param") == 1024)  {
    out <- cpp_encap_kyber1024(pub_key)
  } else {
    pq_stop(c(x = "The suplied public key has invalid parameters."))
  }

  encap <- list(shared_secret = out[[2]],
                encapsulation = out[[1]])
  class(encap) <- c("pqcrypto_encapsulation")

  return(encap)
}
