
#' Key Management - Open
#'
#' Opens a private key or a public key file generated by `write_key()`.
#'
#' @param file_name  The file containing a key to be opened.
#' @param password   If the `file_name`contains an encrypted private key, the decryption password.
#'
#' @return  The public or private key.
#'
#' @export
#'
#' @examples
#' key <- keygen_kyber()
#' path <- tempdir()
#' write_key(key$private, path, "myPassword")
#' prv <- open_key(paste0(path, "/keypair"), "myPassword")
#'
#' identical(key$private, prv)
#'
open_key <- function(file_name, password = NULL) {

  b64_to_raw <- function(txt) {
    if (requireNamespace("openssl", quietly = TRUE)) {
      key <- openssl::base64_decode(txt)
    } else if (requireNamespace("base64enc", quietly = TRUE)) {
      key <- base64enc::base64decode(txt)
    } else {
      pq_msg(c(x="Unable to read the keys if openssl or base64enc packages are not present."))
      return(NULL)
    }
    invisible(key)
  }

  if(!file.exists(file_name)) {
    pq_stop(c(x = "Invalid 'file_name'."))
  }
  keydata <- readLines(file_name)
  base64text <- paste0(keydata[2:(length(keydata)-1)], collapse = "\n")

  if (keydata[1] %in% c("-----BEGIN PUBLIC KEY-----", "-----BEGIN PRIVATE KEY-----")) {
    raw_key <- b64_to_raw(base64text)

  } else if (keydata[1] == "-----BEGIN ENCRYPTED PRIVATE KEY-----") {
    if (!is.null(password)) {
      if (requireNamespace("openssl", quietly = TRUE)) {
        raw_data <- unserialize(b64_to_raw(base64text))
        raw_key <- openssl::aes_cbc_decrypt(raw_data, key_from_pass(as.character(password)))
      } else {
        pq_msg(c(x="Reading encrypted private key files requires openssl package."))
        return(NULL)
      }
    } else {
      pq_stop(c(x="Reading encrypted private key files requires `password` argument to be provided."))
    }
  } else {
    pq_stop(c(x="File does not look like a key file.",
              i="Make sure the `file_name` argument points to a file created by `write_key()`."))
  }

  unserialize(raw_key)
}
