
#' Key Management - Open
#'
#' Opens a private key or a public key file generated by `write_key()`.
#'
#' @param file_name  The file containing a key to be opened.
#' @param password   If the `file_name`contains an encrypted private key, the decryption password.
#'
#' @return  The public or private key.
#'
#' @export
#'
#' @examples
#' key <- keygen_kyber()
#' path <- tempdir()
#' write_key(key$private, path, "myPassword")
#' prv <- open_key(paste0(path, "/keypair"), "myPassword")
#'
#' identical(key$private, prv)
#'
open_key <- function(file_name, password = NULL) {

  if(!file.exists(file_name)) {
    pq_stop(c(x = "Invalid 'file_name'."))
  }
  keydata <- readLines(file_name)
  base64text <- paste0(keydata[2:(length(keydata)-1)], collapse = "\n")

  if (keydata[1] == "-----BEGIN PUBLIC KEY-----") {
    raw_key <- openssl::base64_decode(base64text)
    class(raw_key) <- "pqcrypto_der_public_key"

  } else if (keydata[1] == "-----BEGIN PRIVATE KEY-----") {
    raw_key <- openssl::base64_decode(base64text)
    class(raw_key) <- "pqcrypto_der_private_key"

  } else if (keydata[1] == "-----BEGIN ENCRYPTED PRIVATE KEY-----") {
    if (!is.null(password)) {
      enc_key <- openssl::base64_decode(base64text)
      class(enc_key) <- "pqcrypto_der_encrypted_private_key"

      enc_data <- as.key(enc_key)
      raw_key <- openssl::aes_cbc_decrypt(enc_data, key_from_pass(as.character(password)))
      class(raw_key) <- "pqcrypto_der_private_key"

    } else {
      pq_stop(c(x="Reading encrypted private key files requires `password` argument to be provided."))
    }
  } else {
    pq_stop(c(x="File does not look like a key file.",
              i="Make sure the `file_name` argument points to a file created by `write_key()`."))
  }

  as.key(raw_key)
}
